name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Contar commits
        run: git rev-list --count HEAD

      - name: Gerar Snake GIF
        uses: Platane/snk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # <— adiciona o token aqui
        with:
          github_user_name: Tallesco201
          gif_out_path: dist/github-contribution-grid-snake.gif
          range: 365                                  # opcional: últimos 365 dias

      - name: Listar dist/
        run: ls -lha dist

      - name: Publicar no GitHub Pages (branch output)
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
