name: Atualiza Snake GIF

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Preparar dist
        run: mkdir -p dist

      - name: Gerar Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: Tallesco201
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Listar dist/ no runner
        run: ls -lha dist

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
